FROM nginx:latest

WORKDIR /usr/share/nginx/html

COPY index.html /usr/share/nginx/html
COPY Images /usr/share/nginx/html
COPY css /usr/share/nginx/html

EXPOSE 8080

CMD [ "nginx", "-g", "daemon off;" ]
